"""init

Revision ID: 4c36f7efbf14
Revises: 0fc633c0f2d2
Create Date: 2026-03-20 03:14:03.178152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c36f7efbf14'
down_revision: Union[str, Sequence[str], None] = '0fc633c0f2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bankruptcy_statement', 'case_date_last',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'bankruptcy_statement', ['id'])
    op.alter_column('electronic_case', 'document_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('electronic_case', 'document_date_last',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'electronic_case', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'electronic_case', type_='unique')
    op.alter_column('electronic_case', 'document_date_last',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('electronic_case', 'document_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'bankruptcy_statement', type_='unique')
    op.alter_column('bankruptcy_statement', 'case_date_last',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
