"""added_ix

Revision ID: 58c3418d006c
Revises: 4c36f7efbf14
Create Date: 2026-03-20 05:17:09.778148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c3418d006c'
down_revision: Union[str, Sequence[str], None] = '4c36f7efbf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bankruptcy_statement_case_number', 'bankruptcy_statement', ['case_number'], unique=False)
    op.create_index('ix_bankruptcy_statement_inn', 'bankruptcy_statement', ['inn'], unique=False)
    op.create_index('ix_electronic_case_case_number', 'electronic_case', ['case_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_electronic_case_case_number', table_name='electronic_case')
    op.drop_index('ix_bankruptcy_statement_inn', table_name='bankruptcy_statement')
    op.drop_index('ix_bankruptcy_statement_case_number', table_name='bankruptcy_statement')
    # ### end Alembic commands ###
